In [11]:
from Utils.common.custerReadFile import read_multi_csv
import re
import numpy as np 
from numpy import logical_or
from Params.path_params import Data_path
import pandas as pd
import time
import datetime

In [2]:
data_dir = "{0}/jiufu_chk_csv".format(Data_path)

In [3]:
df = read_multi_csv(data_dir)

In [7]:
df['time'] = pd.to_datetime(df['timestamp'], unit='ms', utc=True)

In [8]:
df.head(10)

,event_id,maxent_id,timestamp,type,time
0,3993f645-11f2-4c78-914c-c93199ad7b34,2ed9d84bdae7e8b381c09b44315791a1,1515495309750,create_account,2018-01-09 10:55:09.750000+00:00
1,1b0a9b3d-9e80-4a6d-9330-deb3f71f015d,45bd4ca025a2fa8300daa050e5814ce6,1515495310030,update_account,2018-01-09 10:55:10.030000+00:00
2,420f848a-64e8-400c-a98d-5c24ae99ed39,9c0cf6d5a6bcc353781d3c5a1ea4bd47,1515495310462,transaction,2018-01-09 10:55:10.462000+00:00
3,00d88a02-edad-4d98-9d5a-64031f53f239,60e3badecf6fec557db5f12f501da1ce,1515495310475,transaction,2018-01-09 10:55:10.475000+00:00
4,0386a175-862b-4357-a833-db2c26a56ed8,a792449284bc2c70c2244327ef5b1fe1,1515495310883,update_account,2018-01-09 10:55:10.883000+00:00
5,881316e3-f129-470c-b213-95a949b33990,d40be94b6d0e89fc69bcaa08f79a26f1,1515495311066,login,2018-01-09 10:55:11.066000+00:00
6,5d9ab366-3be2-49c0-b9e2-cf0297e4400b,cb53d79aefe06b92330a56ed2d1d0dd7,1515495311316,transaction,2018-01-09 10:55:11.316000+00:00
7,1380f58c-9960-4a47-b37f-9c06d1c0e71c,34bc4de9097e33044bc124e473202e8e,1515495311573,login,2018-01-09 10:55:11.573000+00:00
8,bc50545e-99f4-4ba8-beae-c3f6cc542221,0d97529c5f023863062e702734d5c9cc,1515495311574,quota,2018-01-09 10:55:11.574000+00:00
9,c20ef00a-badf-4071-9710-bd587d7d26d0,582814531d5054a3ca6b2083d1762a48,1515495311950,quota,2018-01-09 10:55:11.950000+00:00

In [9]:
df.dtypes

event_id                  object
maxent_id                 object
timestamp                  int64
type                      object
time         datetime64[ns, UTC]
dtype: object

In [17]:
df.loc[(df.time > '2018-01-19 03:00:00') & (df.time < '2018-01-20 03:00:00')].head(10)

,event_id,maxent_id,timestamp,type,time
3221,3dd8a8c6-83f2-4612-aaf9-ec5ef7b68ea4,e6f8939b3a2f71a7acd2c2b8985f283c,1516332000523,update_account,2018-01-19 03:20:00.523000+00:00
3222,77e3e307-5dd6-4fe3-ac61-43cf36541994,ae1493bd719d479adf4e8e555901dd9a,1516332001765,login,2018-01-19 03:20:01.765000+00:00
3223,faec522b-c96f-48f5-a277-d2e776367c65,3d61dfe935248776a3267aea8ce3286a,1516332001936,update_account,2018-01-19 03:20:01.936000+00:00
3224,08c837bd-4ec6-4c25-8e3f-7359bde0b0e7,7088c8b02c1110fb4219275c80816895,1516332001960,transaction,2018-01-19 03:20:01.960000+00:00
3225,e52c0089-b173-4d9b-9bc0-597864dc2096,0b9bf2299f69f12c455769a1151d889b,1516332002221,quota,2018-01-19 03:20:02.221000+00:00
3226,5ed0d6f6-de0e-4043-b6ce-675fb0d8f829,2a5693177f9be08fd675c138b861031c,1516332002293,login,2018-01-19 03:20:02.293000+00:00
3227,507b6b65-a6a3-432a-b78f-60841a827129,ddf1c8f68ef9fbd4f33586f7cdfc6d47,1516332002732,login,2018-01-19 03:20:02.732000+00:00
3228,a099818c-5e18-409b-93ef-b5a2b361f153,dd29052894b18c756c3c70c5fd39e55f,1516332002867,login,2018-01-19 03:20:02.867000+00:00
3229,0a98e1ba-640d-40fa-b4bd-2c91a614dd86,9651ade93412e93ee03cee299ccde9d4,1516332002929,quota,2018-01-19 03:20:02.929000+00:00
3230,fc768ca8-f6fa-43db-8153-c403d3bf70c1,6d0dfe05beb0e296260357ca6d832e52,1516332003087,quota,2018-01-19 03:20:03.087000+00:00

In [18]:
df.loc[(df.time > '2018-01-19 03:00:00') & (df.time < '2018-01-20 03:00:00')].shape

(199126, 5)

In [21]:
df1 = df.loc[(df.time > '2018-01-19 03:00:00') & (df.time < '2018-01-20 03:00:00')].drop('timestamp', axis=1).reset_index(drop=True)

In [22]:
df1.head(10)

,event_id,maxent_id,type,time
0,3dd8a8c6-83f2-4612-aaf9-ec5ef7b68ea4,e6f8939b3a2f71a7acd2c2b8985f283c,update_account,2018-01-19 03:20:00.523000+00:00
1,77e3e307-5dd6-4fe3-ac61-43cf36541994,ae1493bd719d479adf4e8e555901dd9a,login,2018-01-19 03:20:01.765000+00:00
2,faec522b-c96f-48f5-a277-d2e776367c65,3d61dfe935248776a3267aea8ce3286a,update_account,2018-01-19 03:20:01.936000+00:00
3,08c837bd-4ec6-4c25-8e3f-7359bde0b0e7,7088c8b02c1110fb4219275c80816895,transaction,2018-01-19 03:20:01.960000+00:00
4,e52c0089-b173-4d9b-9bc0-597864dc2096,0b9bf2299f69f12c455769a1151d889b,quota,2018-01-19 03:20:02.221000+00:00
5,5ed0d6f6-de0e-4043-b6ce-675fb0d8f829,2a5693177f9be08fd675c138b861031c,login,2018-01-19 03:20:02.293000+00:00
6,507b6b65-a6a3-432a-b78f-60841a827129,ddf1c8f68ef9fbd4f33586f7cdfc6d47,login,2018-01-19 03:20:02.732000+00:00
7,a099818c-5e18-409b-93ef-b5a2b361f153,dd29052894b18c756c3c70c5fd39e55f,login,2018-01-19 03:20:02.867000+00:00
8,0a98e1ba-640d-40fa-b4bd-2c91a614dd86,9651ade93412e93ee03cee299ccde9d4,quota,2018-01-19 03:20:02.929000+00:00
9,fc768ca8-f6fa-43db-8153-c403d3bf70c1,6d0dfe05beb0e296260357ca6d832e52,quota,2018-01-19 03:20:03.087000+00:00

In [23]:
df1.shape

(199126, 4)

In [24]:
df1.sort_values(by='time')

,event_id,maxent_id,type,time
19672,59df3782-e512-407e-9d63-4b10ff481dfd,a7d431837e34682035cbb578f59c87b5,transaction,2018-01-19 03:00:00.098000+00:00
19673,528742c4-bb80-4257-9b24-2dbbe70cedc9,48c1a654c080bd02d304277607937193,login,2018-01-19 03:00:00.330000+00:00
19674,e3d06a6b-4146-4ed9-99ae-229ff3467c00,d8a7c3868abe325b42dafe54d7fabcb1,quota,2018-01-19 03:00:00.332000+00:00
19675,1125aeb8-0224-4a18-86ca-8d05879cd34e,c0bb3a5382336381748b2dd3afcd8015,transaction,2018-01-19 03:00:00.362000+00:00
19676,dd3e9516-95a3-493a-a3f6-be9252631ee7,55ad1b7b976e3c7f7143d73dd5b1c06b,update_account,2018-01-19 03:00:00.514000+00:00
19677,9b173120-717c-43ba-8870-223c1119932f,2c38cb7d77badc8a280e65c1ab7e0322,transaction,2018-01-19 03:00:00.558000+00:00
19678,ca337d2c-5d32-441c-b575-9fcc090eb7b7,30a3ea5eece3c2c1a254404a19830784,login,2018-01-19 03:00:00.791000+00:00
19679,6aac2a7d-58dc-461b-b604-e870cf5e915a,146ac32741861d0c86a8c4ce12200e52,login,2018-01-19 03:00:00.865000+00:00
19680,eb66d507-1a10-4413-a2b5-2a51405ee8f4,2c771cd0f7e885946656f0d69f8cce5e,quota,2018-01-19 03:00:01.057000+00:00
19681,39b5c65d-d2f1-40e4-98fa-ad26d2fe1c0b,c61c677be339621f4cb70433f270742c,update_account,2018-01-19 03:00:01.174000+00:00
19682,2813b647-e08c-406d-ad03-acc748794504,5c8df9592e99e6e5111440de861bd28c,login,2018-01-19 03:00:01.459000+00:00
19683,810b02d6-78a5-4c1e-bd0a-47790c02a105,06edb5f7c0de5d4f9d8df73836ea75fe,login,2018-01-19 03:00:01.468000+00:00
19684,e6ec90ca-82c1-46d8-867d-ae701b6bc95a,fb8b1cab71292cc53c4ac7f17c34b91f,quota,2018-01-19 03:00:01.856000+00:00
19685,c6bf3e53-a8f7-48d6-a1f3-22b7a6f9778f,2940b4ee3369747af820f30a8a0417dc,update_account,2018-01-19 03:00:01.917000+00:00
19686,dff42012-fe13-41de-bc6a-7ee2dd1c3d0d,a3c7e9fee6d0c05f206d4fb3d0cdc6ff,update_account,2018-01-19 03:00:02.028000+00:00
19687,04564182-def9-4285-b043-163460b15e3e,1f3a0dc997bea39125230f0f103001ad,login,2018-01-19 03:00:02.353000+00:00
19688,681f89a4-6cfd-40d9-bb0e-65fddba6141b,2c771cd0f7e885946656f0d69f8cce5e,quota,2018-01-19 03:00:02.560000+00:00
19689,16fe47b6-5e08-4063-9a26-b29e7a042971,a4df748a4ecfd712a41e1b802ccc01c3,quota,2018-01-19 03:00:03.139000+00:00
19691,6d224f06-7627-4ad6-b2c0-811c02deccdf,be4d7b3262b734f832b3352dd5d193a0,update_account,2018-01-19 03:00:03.191000+00:00
19690,2f182f50-61a4-45bd-b413-99fd062cf38f,24c05e13d1d3d1af6ad69edd60f8e745,login,2018-01-19 03:00:03.247000+00:00
19692,cbe7b163-93fc-423f-9aaf-dbb2dca56838,367fc60eeb1563a51b0798fd6e657c93,update_account,2018-01-19 03:00:03.632000+00:00
19694,a8b3f727-e6ed-461b-bc09-4fba18f361ec,06ba4caec070e8ba49b3132eb12886f6,login,2018-01-19 03:00:04.590000+00:00
19693,add8eda5-d62e-4b1a-9b49-d171a2f3cf6d,c2f2cef97e49036c8e7e77416b3b75b2,quota,2018-01-19 03:00:04.614000+00:00
19695,eeeaa7c4-e239-43f5-89ca-9a37d771741a,a53ca22357bf5c09d49c860665edd11a,login,2018-01-19 03:00:04.723000+00:00
19696,64e06950-99d9-448c-ba86-c96700aecfc1,c61c677be339621f4cb70433f270742c,update_account,2018-01-19 03:00:04.902000+00:00
19697,647f93ca-8fc6-4a43-a395-9088946b5732,d9dd6a912fda8856f4151dec3f171a33,create_account,2018-01-19 03:00:05.019000+00:00
19698,9841e893-928e-49fc-a9b2-4ab1b15e81aa,e0ac842aa67d5274a598862e7e5c14b4,login,2018-01-19 03:00:05.264000+00:00
19699,deb91a32-6638-4e46-a4df-c7cc06f9fba9,d8b613a97138adcc87c41ead60c32ec5,login,2018-01-19 03:00:05.586000+00:00
19700,becd914a-9d00-4e2c-8a6a-71b054831d4f,9faab7ca9602275d9ba0065b66bbd024,login,2018-01-19 03:00:05.587000+00:00
19701,169e2e14-2ef9-4df3-b64e-0f789539bd63,490f0fbce8546afb3e52e1e27093dd0f,login,2018-01-19 03:00:05.652000+00:00
...,...,...,...,...
166347,4627a23a-c304-4975-ae60-17becc5e6873,0fc3da8a5dda46dff24e99ba10b77310,login,2018-01-20 02:59:50.780000+00:00
166348,aa01be68-d257-4566-a90c-94c1d32f962b,cc41110d1d52dccdcc9166e03720ec55,quota,2018-01-20 02:59:50.818000+00:00
166349,f231422b-7cb3-4fbf-97fd-672c1c1cd973,9104056afa27b3ed39195165ba904b1f,login,2018-01-20 02:59:50.884000+00:00
166350,546837c1-fc99-4d71-9973-e0f9e0c6f244,131c30c3b34c47aa7384915d18026ec2,login,2018-01-20 02:59:50.903000+00:00
166351,3e776c0f-d758-4c33-8cf9-03012b848fef,c517219b446c5ef4934d8e879b7a4115,login,2018-01-20 02:59:51.133000+00:00
166352,e8316b29-02fe-4706-8f77-5c33d77987fa,f016f8ac1af69d79becdcf048e1f9e8d,update_account,2018-01-20 02:59:51.356000+00:00
166353,e918744a-ec3c-44e4-a3e4-54d49f6af192,87b85506bbbfd62c531142c566894394,quota,2018-01-20 02:59:51.546000+00:00
166354,9a62409f-3b83-4de2-83ae-e6796562c541,0a06b32f697ab4cc46f287c81de66b5a,login,2018-01-20 02:59:52.083000+00:00
166355,fc0f30ef-4f4d-4ac6-accb-a6e34e47e73d,c19710ba6d5de2cc79a8f68ffb9c56ca,transaction,2018-01-20 02:59:52.303000+00:00
166356,e53b2620-98f1-462c-97ac-0eb07a6254da,df17cb40f954c5237f3e1d252d470fb8,login,2018-01-20 02:59:52.929000+00:00
166357,a5972a15-5afa-4f65-ac69-deff45899609,87b85506bbbfd62c531142c566894394,quota,2018-01-20 02:59:53.606000+00:00
166358,b44cf29f-0067-42a7-bf8c-62e009c89b00,3672ea03f561d1ec62695d7495438bd8,create_account,2018-01-20 02:59:53.734000+00:00
166359,f2890348-8563-446f-bc9c-abc570501a1c,8f8ca1a72839ed680ec49fb63ed4abb8,login,2018-01-20 02:59:54.192000+00:00
166361,77adbce6-4c15-4bef-975b-052efb104b39,1c26a662ee31680e452933ae735f7c6e,login,2018-01-20 02:59:54.488000+00:00
166360,0deaa952-2fbd-40c4-a646-6f4e3cdb55e7,d1e6754922455e2d680c421afcd51240,login,2018-01-20 02:59:54.533000+00:00
166362,29a6899c-468c-4235-a8ae-fc3cdd5c7d5a,e4616abe612ac5c2e69ac40ebcdff1f3,create_account,2018-01-20 02:59:54.761000+00:00
166363,bbf17c46-e9bc-4716-b849-fa98e7ff9771,40fb4b3b3de636b06ea6287b614c8610,login,2018-01-20 02:59:54.840000+00:00
166364,666e5459-2701-40da-a148-0fecde7bf585,4e4d275e20c460ec44790cf729270dd4,create_account,2018-01-20 02:59:55.614000+00:00
166365,1086d153-ef57-4d94-b43e-f9be7854c2f7,66f15aacd3b29e579ffc069b481650d2,create_account,2018-01-20 02:59:56.096000+00:00
166366,1b84cb52-b14c-4c5b-ae4a-115ee8f04861,ebb1dcbec72b1c3945f84d074573551d,login,2018-01-20 02:59:57.437000+00:00
166367,40651322-b7b1-4aac-a69f-dc0e292627cd,f89c12cc4936d8fca45c24ce0b6061df,transaction,2018-01-20 02:59:57.768000+00:00
166368,817173c4-dc08-46f4-b1fe-44ea57613eb8,c5196e1e52a8ce4bb5639fee834870d5,login,2018-01-20 02:59:58.549000+00:00
166369,8e248509-e93e-4bb3-a4d7-4c823e0b72af,03b3038e403397bf615a35a4a6e62ef8,create_account,2018-01-20 02:59:58.704000+00:00
166370,274cb3de-abb8-4c1a-9321-7e5846bffd8f,0e9f570afd69584c4608e7834693a1aa,login,2018-01-20 02:59:58.816000+00:00
166372,b50b6a1f-b1a1-42c5-9bd0-4681c734c95b,4a88ad93aad8efa3e0f9f4512bb9c09d,login,2018-01-20 02:59:58.887000+00:00
166371,f9179493-7113-4124-b56e-395d29eed972,7246bf6cfc9c1e4ef4a5f18e0eebd3cd,login,2018-01-20 02:59:58.893000+00:00
166373,8c6f16ee-d9f9-46dd-b7cf-a3f5079ed689,642b5016b46de47c4d727bd2d65f555f,quota,2018-01-20 02:59:59.028000+00:00
166375,b066a292-0381-465b-a57c-68e73df897bd,131c30c3b34c47aa7384915d18026ec2,login,2018-01-20 02:59:59.257000+00:00
166374,0836767d-7250-48e0-a8ee-7b0a19a54400,85d970b97102e7786420c2aee96bf799,login,2018-01-20 02:59:59.265000+00:00
166376,a29fb97c-3c1d-4732-bfae-5724b77d8ec3,e4b94525c7e5dd4a6f7e24ff1ae3eb3e,quota,2018-01-20 02:59:59.906000+00:00